#!/usr/bin/env python3
"""
Unit 3 (1BHK Executive Suite + Balcony) - CAD-aligned GLB generator  (v2)

Coordinate system (metres, glTF Y-up, plan is NOT mirrored):
    +X = east  (plan: right)      +Z = south (plan: down)      +Y = up
    Origin = interior face of the NORTH wall / WEST wall corner of the living room.

Measured from the drawing (scale from balcony 16'-9" = 5.10 m  ->  78.4 px/m):
    interior 8.35 x 5.10 | balcony 1.37 x 5.10 | ext. wall 0.23 | partitions 0.12
    living/bedroom partition Z 2.34-2.46 | bed/toilet wall X 4.16-4.28
    toilet/kitchen wall X 5.90-6.02      | shaft wall Z 4.30-4.42
    entry door leaf 0.85 | bedroom door leaf 0.80 | toilet door leaf 0.70 | all 2.10 high

Fixes vs. v1:
  * every wall is generated by wall_run(): piers / sills / lintels split automatically
    -> openings always match the door/window that fills them (no gaps, no overlaps)
  * walls abut instead of overlapping -> no coplanar top faces (z-fighting)
  * kitchen counter built from separate pieces around a real sink cut-out
  * cylinders were lying on their side in v1 (trimesh cylinders run along Z) -> now Y-up
  * glass now uses alphaMode BLEND (v1 glass rendered opaque)
  * layout re-positioned from plan (bed head at south wall, wardrobe, WM/fridge, shaft,
    toilet fittings, balcony door only on dining side, etc.)
  * ceiling is a single-sided quad: visible from inside, invisible from above (orbit-friendly)

Usage:  python generate_unit3_glb.py [--out models/unit_3.glb] [--ground] [--no-ceiling]
"""
import os
import argparse
import numpy as np
import trimesh
from trimesh.visual.material import PBRMaterial

# ----------------------------------------------------------------- constants
H_WALL = 2.85
T_EXT = 0.23
T_INT = 0.12
T_EAST = 0.20
H_DOOR = 2.10
FT = 0.12                       # floor build-up thickness (below Y=0)
W_IN, D_IN = 8.35, 5.10         # interior size (X, Z)
BAL_X0, BAL_X1 = W_IN + T_EAST, 9.92

# partition lines
ZP0, ZP1 = 2.34, 2.46           # living / bedroom partition
XB0, XB1 = 4.16, 4.28           # bedroom / toilet
XK0, XK1 = 5.90, 6.02           # toilet / kitchen
ZS0, ZS1 = 4.30, 4.42           # toilet / shaft
ZW0, ZW1 = 3.15, 3.27           # washing-machine nook

PARTS = []                      # (mesh, name)
_used = {}


# ----------------------------------------------------------------- materials
def mat(name, rgb, rough, metal=0.0, alpha=1.0, emissive=None, double=False):
    kw = dict(name=name, baseColorFactor=[*rgb, alpha], roughnessFactor=rough, metallicFactor=metal)
    if alpha < 1.0:
        kw.update(alphaMode="BLEND", doubleSided=True)
    elif double:
        kw.update(doubleSided=True)
    if emissive is not None:
        kw["emissiveFactor"] = emissive
    return PBRMaterial(**kw)


M = dict(
    wall=mat("Wall_Cashmere", [0.66, 0.62, 0.56], 0.88, 0.01),
    accent=mat("Wall_Sage", [0.20, 0.30, 0.22], 0.80, 0.02),
    slat=mat("Oak_Slat", [0.58, 0.38, 0.20], 0.48, 0.02),
    slat_back=mat("Slat_Backing", [0.10, 0.10, 0.11], 0.95),
    skirt=mat("Skirting_Frames", [0.16, 0.11, 0.08], 0.45, 0.05),
    rug_l=mat("Rug_Living", [0.62, 0.56, 0.48], 0.96),
    rug_d=mat("Rug_Dining", [0.52, 0.46, 0.38], 0.96),
    rug_b=mat("Rug_Bed", [0.60, 0.54, 0.46], 0.96),
    parquet=mat("Floor_Parquet", [0.55, 0.35, 0.19], 0.40, 0.04),
    bal_floor=mat("Floor_Balcony", [0.50, 0.36, 0.26], 0.75, 0.02),
    tiles=mat("Floor_Tiles", [0.32, 0.30, 0.28], 0.30, 0.06),
    concrete=mat("Concrete", [0.42, 0.42, 0.41], 0.9),
    ceiling=mat("Ceiling", [0.90, 0.88, 0.86], 0.92, double=False),
    glass=mat("Glass", [0.88, 0.94, 0.98], 0.03, 0.05, alpha=0.22),
    mirror=mat("Mirror", [0.80, 0.85, 0.88], 0.05, 0.9),
    black=mat("Metal_Black", [0.08, 0.08, 0.09], 0.35, 0.85),
    walnut=mat("Walnut", [0.24, 0.14, 0.08], 0.38, 0.03),
    door=mat("Door_Oak", [0.48, 0.32, 0.18], 0.44, 0.02),
    leather=mat("Leather_Cognac", [0.44, 0.18, 0.06], 0.62, 0.01),
    sofa=mat("Fabric_Sofa", [0.16, 0.20, 0.18], 0.88, 0.01),
    ochre=mat("Velvet_Ochre", [0.66, 0.40, 0.12], 0.75, 0.01),
    sage=mat("Velvet_Sage", [0.22, 0.32, 0.22], 0.80, 0.01),
    linen=mat("Bed_Linen", [0.88, 0.86, 0.82], 0.90, 0.01),
    throw=mat("Bed_Throw", [0.48, 0.16, 0.08], 0.85, 0.01),
    headboard=mat("Headboard", [0.38, 0.34, 0.30], 0.92),
    upper=mat("Cab_Upper", [0.65, 0.60, 0.52], 0.45, 0.02),
    steel=mat("Steel_Appliance", [0.60, 0.62, 0.65], 0.22, 0.92),
    white_app=mat("Appliance_White", [0.88, 0.88, 0.90], 0.30, 0.1),
    marble=mat("Marble", [0.92, 0.90, 0.86], 0.14, 0.04),
    brass=mat("Brass", [0.82, 0.68, 0.36], 0.28, 0.88),
    ceramic=mat("Ceramic", [0.94, 0.94, 0.94], 0.10, 0.05),
    hob=mat("Hob_Glass", [0.03, 0.03, 0.035], 0.08, 0.2),
    screen=mat("Screen", [0.02, 0.02, 0.025], 0.05, 0.3),
    ground=mat("Ground", [0.18, 0.30, 0.14], 0.88, 0.02),
    leaf=mat("Plant_Green", [0.12, 0.30, 0.10], 0.65, 0.01),
    leaf2=mat("Plant_Dark", [0.07, 0.20, 0.08], 0.65, 0.01),
    pot=mat("Planter", [0.48, 0.24, 0.14], 0.75, 0.02),
    canvas=mat("Art_Canvas", [0.40, 0.48, 0.44], 0.70, 0.02),
    lamp_shade=mat("Lamp_Shade", [0.85, 0.80, 0.70], 0.9),
    light=mat("Downlight", [1, 1, 1], 0.5, 0.0, emissive=[1.0, 0.93, 0.78]),
)


# ----------------------------------------------------------------- primitives
def _emit(mesh, material, name):
    """un-merge, add planar UVs (world-space metres) and register the mesh."""
    mesh.unmerge_vertices()
    tri = mesh.vertices[mesh.faces]
    fn = np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0])
    fn /= (np.linalg.norm(fn, axis=1, keepdims=True) + 1e-12)
    n = np.abs(np.repeat(fn, 3, axis=0))            # faces are ordered 3 verts each
    v = mesh.vertices
    uv = np.where((n[:, 1:2] >= n[:, 0:1]) & (n[:, 1:2] >= n[:, 2:3]), v[:, [0, 2]],
                  np.where(n[:, 0:1] >= n[:, 2:3], v[:, [2, 1]], v[:, [0, 1]]))
    mesh.visual = trimesh.visual.TextureVisuals(uv=uv.astype(np.float32), material=material)
    k = _used.get(name, 0)
    _used[name] = k + 1
    PARTS.append((mesh, name if k == 0 else f"{name}_{k}"))


def box(name, material, x0, x1, y0, y1, z0, z1):
    sx, sy, sz = x1 - x0, y1 - y0, z1 - z0
    if min(sx, sy, sz) <= 1e-6:
        raise ValueError(f"degenerate box {name}: {sx:.4f},{sy:.4f},{sz:.4f}")
    m = trimesh.creation.box(extents=[sx, sy, sz])
    m.apply_translation([(x0 + x1) / 2, (y0 + y1) / 2, (z0 + z1) / 2])
    _emit(m, material, name)


def bx(axis, name, material, a0, a1, y0, y1, c0, c1):
    """box where (a0,a1) run along `axis` ('x' or 'z') and (c0,c1) is the cross direction."""
    if axis == "x":
        box(name, material, a0, a1, y0, y1, c0, c1)
    else:
        box(name, material, c0, c1, y0, y1, a0, a1)


def cyl(name, material, cx, cy, cz, r, h, axis="y", sections=32, scale=(1, 1, 1)):
    """cylinder centred at (cx,cy,cz). axis = direction of its length (trimesh default is Z)."""
    m = trimesh.creation.cylinder(radius=r, height=h, sections=sections)
    if axis == "y":
        m.apply_transform(trimesh.transformations.rotation_matrix(np.pi / 2, [1, 0, 0]))
    elif axis == "x":
        m.apply_transform(trimesh.transformations.rotation_matrix(np.pi / 2, [0, 1, 0]))
    m.apply_scale(scale)
    m.apply_translation([cx, cy, cz])
    _emit(m, material, name)


def ball(name, material, cx, cy, cz, r, sy=1.0):
    m = trimesh.creation.icosphere(subdivisions=2, radius=r)
    m.apply_scale([1, sy, 1])
    m.apply_translation([cx, cy, cz])
    _emit(m, material, name)


def ceiling_quad(name, x0, x1, z0, z1, y=H_WALL):
    """single-sided quad whose normal faces DOWN (seen from inside, culled from above)."""
    v = np.array([[x0, y, z0], [x1, y, z0], [x1, y, z1], [x0, y, z1]], dtype=float)
    m = trimesh.Trimesh(vertices=v, faces=[[0, 1, 2], [0, 2, 3]], process=False)
    _emit(m, M["ceiling"], name)


# ----------------------------------------------------------------- architecture helpers
def wall_run(name, material, axis, a0, a1, c0, c1, openings=(), y0=-FT, y1=H_WALL):
    """Wall along `axis` from a0..a1, thickness c0..c1.
    openings = [(start, end, sill_height, head_height)] -> piers, sill piece, lintel piece."""
    def put(tag, s, e, ya, yb):
        if e - s > 1e-6 and yb - ya > 1e-6:
            bx(axis, f"{name}_{tag}", material, s, e, ya, yb, c0, c1)
    cur = a0
    for k, (s, e, sill, head) in enumerate(sorted(openings)):
        put(f"pier{k}", cur, s, y0, y1)
        put(f"sill{k}", s, e, y0, sill)
        put(f"lintel{k}", s, e, head, y1)
        cur = e
    put(f"pier{len(openings)}", cur, a1, y0, y1)


def door(name, axis, wc0, wc1, a0, a1, hinge_at_end=True):
    """Closed door: frame (jambs+head) sits INSIDE the structural opening a0..a1, leaf fills it.
    Leaf width = (a1-a0) - 2*0.04 frame."""
    fb, c = 0.04, (wc0 + wc1) / 2
    f0, f1 = wc0 - 0.012, wc1 + 0.012
    bx(axis, f"{name}_JambA", M["skirt"], a0, a0 + fb, 0, H_DOOR, f0, f1)
    bx(axis, f"{name}_JambB", M["skirt"], a1 - fb, a1, 0, H_DOOR, f0, f1)
    bx(axis, f"{name}_Head", M["skirt"], a0 + fb, a1 - fb, H_DOOR - fb, H_DOOR, f0, f1)
    la0, la1 = a0 + fb, a1 - fb
    bx(axis, f"{name}_Leaf", M["door"], la0, la1, 0.010, H_DOOR - fb, c - 0.02, c + 0.02)
    hx = (la0 + 0.07) if hinge_at_end else (la1 - 0.07)
    for side in (-1, 1):
        face = c + side * 0.02
        lo, hi = sorted((face, face + side * 0.006))
        bx(axis, f"{name}_Rose{side}", M["brass"], hx - 0.02, hx + 0.02, 0.96, 1.12, lo, hi)
        lo, hi = sorted((face + side * 0.006, face + side * 0.040))
        bx(axis, f"{name}_Stem{side}", M["brass"], hx - 0.008, hx + 0.008, 1.03, 1.05, lo, hi)
        lo, hi = sorted((face + side * 0.030, face + side * 0.042))
        d = -1 if hinge_at_end else 1
        s0, s1 = sorted((hx - 0.008, hx - 0.008 + d * 0.12))
        bx(axis, f"{name}_Lever{side}", M["brass"], s0, s1, 1.03, 1.05, lo, hi)


def glazed_x(prefix, xc, z0, z1, y0, y1, sashes=2, depth=0.07, bar=0.05):
    """Window / sliding door in a wall whose thickness runs along X. Fills opening z0..z1, y0..y1."""
    h = depth / 2
    box(prefix + "_FrmL", M["black"], xc - h, xc + h, y0, y1, z0, z0 + bar)
    box(prefix + "_FrmR", M["black"], xc - h, xc + h, y0, y1, z1 - bar, z1)
    box(prefix + "_FrmT", M["black"], xc - h, xc + h, y1 - bar, y1, z0 + bar, z1 - bar)
    box(prefix + "_FrmB", M["black"], xc - h, xc + h, y0, y0 + bar, z0 + bar, z1 - bar)
    iz0, iz1, iy0, iy1 = z0 + bar, z1 - bar, y0 + bar, y1 - bar
    if sashes == 1:
        box(prefix + "_Glass", M["glass"], xc - 0.006, xc + 0.006, iy0, iy1, iz0, iz1)
        return
    w, sb, tx = (iz1 - iz0) / sashes, 0.04, 0.014
    for i in range(sashes):
        xo = xc + (i - (sashes - 1) / 2) * 0.034
        s0 = iz0 + i * w - (0.02 if i > 0 else 0)
        s1 = iz0 + (i + 1) * w + (0.02 if i < sashes - 1 else 0)
        p = f"{prefix}_S{i}"
        box(p + "_L", M["black"], xo - tx, xo + tx, iy0, iy1, s0, s0 + sb)
        box(p + "_R", M["black"], xo - tx, xo + tx, iy0, iy1, s1 - sb, s1)
        box(p + "_T", M["black"], xo - tx, xo + tx, iy1 - sb, iy1, s0 + sb, s1 - sb)
        box(p + "_B", M["black"], xo - tx, xo + tx, iy0, iy0 + sb, s0 + sb, s1 - sb)
        box(p + "_Glass", M["glass"], xo - 0.005, xo + 0.005, iy0 + sb, iy1 - sb, s0 + sb, s1 - sb)


def skirt(name, axis, a0, a1, face, side):
    """skirting 90 mm x 12 mm on a wall face. side=+1 -> projects toward +c."""
    lo, hi = sorted((face, face + side * 0.012))
    bx(axis, name, M["skirt"], a0, a1, 0, 0.09, lo, hi)


def fronts(prefix, fmat, fx0, fx1, out, za, zb, y0, y1, n, mode, hy=None, gap=0.004):
    """cabinet fronts (+brass handles). out=-1: face toward -X, +1: toward +X."""
    hx = (fx0 - 0.03, fx0) if out < 0 else (fx1, fx1 + 0.03)
    if mode == "drawers":
        h = (y1 - y0) / n
        for i in range(n):
            ya, yb = y0 + i * h + gap / 2, y0 + (i + 1) * h - gap / 2
            box(f"{prefix}_Dr{i}", fmat, fx0, fx1, ya, yb, za + gap / 2, zb - gap / 2)
            zc, yc = (za + zb) / 2, yb - 0.045
            box(f"{prefix}_DrH{i}", M["brass"], hx[0], hx[1], yc - 0.006, yc + 0.006, zc - 0.13, zc + 0.13)
    else:
        w = (zb - za) / n
        hy = hy or (y1 - 0.32, y1 - 0.06)
        for i in range(n):
            a, b = za + i * w + gap / 2, za + (i + 1) * w - gap / 2
            box(f"{prefix}_Door{i}", fmat, fx0, fx1, y0, y1, a, b)
            zh = (a + 0.05) if i % 2 else (b - 0.05)
            box(f"{prefix}_DoorH{i}", M["brass"], hx[0], hx[1], hy[0], hy[1], zh - 0.006, zh + 0.006)


# ----------------------------------------------------------------- building shell
def build_shell(ceiling=True):
    # ---- structure + floors
    box("Slab", M["concrete"], -T_EXT, BAL_X1, -0.30, -FT, -T_EXT, D_IN + T_EXT)
    box("Floor_LivingDining", M["parquet"], 0, W_IN, -FT, 0, 0, ZP0)
    box("Floor_Bedroom", M["parquet"], 0, XB0, -FT, 0, ZP0, D_IN)
    box("Floor_Toilet", M["tiles"], XB0, XK1 + T_INT, -FT, 0, ZP0, ZS0)
    box("Floor_Shaft", M["concrete"], XB0, XK1 + T_INT, -FT, 0, ZS0, D_IN)
    box("Floor_Kitchen", M["tiles"], XK1 + T_INT, W_IN, -FT, 0, ZP0, D_IN)
    box("Floor_Balcony", M["bal_floor"], BAL_X0, BAL_X1, -FT, 0, 0, D_IN)
    box("Threshold_Slider", M["steel"], W_IN, BAL_X0, -FT, 0, 0.15, 2.36)

    # ---- exterior walls
    wall_run("Wall_North", M["wall"], "x", -T_EXT, BAL_X1, -T_EXT, 0.0)            # incl. balcony party wall
    wall_run("Wall_South", M["wall"], "x", -T_EXT, BAL_X0, D_IN, D_IN + T_EXT)
    wall_run("Wall_West", M["wall"], "z", 0.0, D_IN, -T_EXT, 0.0,
             openings=[(0.15, 1.08, -FT, H_DOOR),            # entry door (leaf 0.85)
                       (2.87, 4.08, 0.90, H_DOOR)])         # bedroom window
    wall_run("Wall_East", M["wall"], "z", 0.0, D_IN, W_IN, BAL_X0,
             openings=[(0.15, 2.36, -FT, H_DOOR),            # balcony slider (dining)
                       (2.68, 3.80, 1.10, H_DOOR)])         # kitchen window above counter
    # ---- interior partitions (0.12)
    wall_run("Part_LivBed", M["wall"], "x", 0.0, XK1 + T_INT + 0.82, ZP0, ZP1,
             openings=[(3.07, 3.95, -FT, H_DOOR),            # bedroom door (leaf 0.80)
                       (5.00, 5.78, -FT, H_DOOR)])            # toilet door  (leaf 0.70)
    wall_run("Part_BedToilet", M["wall"], "z", ZP1, D_IN, XB0, XB1)
    wall_run("Part_ToiletKitchen", M["wall"], "z", ZP1, D_IN, XK0, XK1)
    wall_run("Part_Shaft", M["wall"], "x", XB1, XK0, ZS0, ZS1)
    wall_run("Part_WMnook", M["wall"], "x", XK1, XK1 + 0.82, ZW0, ZW1)

    # ---- doors & windows
    door("Door_Entry", "z", -T_EXT, 0.0, 0.15, 1.08, hinge_at_end=False)
    door("Door_Bedroom", "x", ZP0, ZP1, 3.07, 3.95)
    door("Door_Toilet", "x", ZP0, ZP1, 5.00, 5.78)
    glazed_x("Win_Bedroom", -T_EXT / 2, 2.87, 4.08, 0.90, H_DOOR, sashes=2)
    box("Win_Bedroom_Sill", M["slat"], 0.0, 0.06, 0.90, 0.93, 2.87, 4.08)
    glazed_x("Slider_Balcony", (W_IN + BAL_X0) / 2, 0.15, 2.36, 0.0, H_DOOR, sashes=2)
    glazed_x("Win_Kitchen", (W_IN + BAL_X0) / 2, 2.68, 3.80, 1.10, H_DOOR, sashes=2)

    # ---- skirting
    skirt("Sk_Liv_N_a", "x", 0, 4.77, 0.0, +1)
    skirt("Sk_Liv_N_b", "x", 5.20, W_IN, 0.0, +1)
    skirt("Sk_Liv_W", "z", 1.12, ZP0, 0.0, +1)
    skirt("Sk_Liv_P_a", "x", 0, 3.03, ZP0, -1)
    skirt("Sk_Liv_P_b", "x", 3.99, 4.96, ZP0, -1)
    skirt("Sk_Liv_P_c", "x", 5.82, 6.84, ZP0, -1)
    skirt("Sk_Bed_W", "z", ZP1, D_IN, 0.0, +1)
    skirt("Sk_Bed_S", "x", 0, XB0, D_IN, -1)
    skirt("Sk_Bed_P_a", "x", 0, 3.03, ZP1, +1)
    skirt("Sk_Bed_P_b", "x", 3.99, XB0, ZP1, +1)
    skirt("Sk_Bed_E", "z", ZP1 + 0.0, 3.30, XB0, -1)

    # ---- ceiling
    if ceiling:
        ceiling_quad("Ceiling_Interior", 0, W_IN, 0, D_IN)
        ceiling_quad("Ceiling_Balcony", BAL_X0, BAL_X1, 0, D_IN)
    # downlights
    pts = [(x, z) for x in (1.2, 2.7, 4.2) for z in (0.7, 1.8)]
    pts += [(5.9, 0.7), (7.4, 0.7), (5.9, 1.7), (7.4, 1.7), (1.0, 3.4), (2.6, 3.4), (1.0, 4.5), (2.6, 4.5),
            (7.0, 3.0), (7.0, 4.4), (5.1, 3.4)]
    for i, (x, z) in enumerate(pts):
        cyl(f"Downlight_{i}", M["light"], x, H_WALL - 0.008, z, 0.045, 0.016)


# ----------------------------------------------------------------- living / dining
def build_living():
    # acoustic slat panel behind sofa (north wall)
    box("Slat_Backing", M["slat_back"], 1.00, 3.20, 0.09, 2.60, 0.0, 0.02)
    for i in range(31):
        x = 1.015 + i * 0.07
        box(f"Slat_{i}", M["slat"], x, x + 0.04, 0.09, 2.60, 0.02, 0.04)
    box("Art_Frame", M["walnut"], 1.55, 2.65, 1.12, 1.80, 0.04, 0.07)
    box("Art_Canvas", M["canvas"], 1.59, 2.61, 1.16, 1.76, 0.07, 0.075)

    # rugs
    box("Rug_Living", M["rug_l"], 1.10, 3.50, 0.0, 0.012, 0.55, 1.85)
    box("Rug_Dining", M["rug_d"], 5.60, 7.75, 0.0, 0.012, 0.10, 1.45)

    # sofa (X 1.12-3.07, Z 0.04-0.84, backrest on north wall)
    for i, (x, z) in enumerate([(1.16, 0.08), (3.03, 0.08), (1.16, 0.80), (3.03, 0.80)]):
        box(f"Sofa_Foot{i}", M["black"], x - 0.02, x + 0.02, 0, 0.12, z - 0.02, z + 0.02)
    box("Sofa_Base", M["sofa"], 1.12, 3.07, 0.12, 0.30, 0.04, 0.84)
    box("Sofa_Back", M["sofa"], 1.32, 2.87, 0.30, 0.80, 0.04, 0.22)
    box("Sofa_ArmL", M["sofa"], 1.12, 1.32, 0.30, 0.60, 0.04, 0.84)
    box("Sofa_ArmR", M["sofa"], 2.87, 3.07, 0.30, 0.60, 0.04, 0.84)
    for i, (a, b) in enumerate([(1.32, 2.09), (2.10, 2.87)]):
        box(f"Sofa_Seat{i}", M["sofa"], a, b, 0.30, 0.44, 0.22, 0.84)
        box(f"Sofa_BackCush{i}", M["sofa"], a + 0.005, b - 0.005, 0.44, 0.78, 0.22, 0.32)
    box("Pillow_Ochre", M["ochre"], 1.40, 1.80, 0.44, 0.76, 0.32, 0.43)
    box("Pillow_Sage", M["sage"], 2.50, 2.82, 0.44, 0.74, 0.32, 0.43)

    # coffee table (X 1.57-2.65, Z 0.96-1.43)
    box("Coffee_Top", M["marble"], 1.57, 2.65, 0.38, 0.41, 0.96, 1.43)
    box("Coffee_Apron", M["walnut"], 1.60, 2.62, 0.34, 0.38, 0.99, 1.40)
    for i, (x, z) in enumerate([(1.62, 1.01), (2.57, 1.01), (1.62, 1.35), (2.57, 1.35)]):
        box(f"Coffee_Leg{i}", M["black"], x, x + 0.03, 0, 0.34, z, z + 0.03)
    box("Coffee_Shelf", M["walnut"], 1.65, 2.57, 0.12, 0.14, 1.01, 1.38)

    # armchair (X 3.72-4.46, Z 0.88-1.58, faces west)
    for i, (x, z) in enumerate([(3.76, 0.92), (4.42, 0.92), (3.76, 1.54), (4.42, 1.54)]):
        box(f"Arm_Leg{i}", M["black"], x - 0.02, x + 0.02, 0, 0.15, z - 0.02, z + 0.02)
    box("Arm_Base", M["leather"], 3.72, 4.46, 0.15, 0.32, 0.88, 1.58)
    box("Arm_Back", M["leather"], 4.26, 4.46, 0.32, 0.85, 0.88, 1.58)
    box("Arm_RestN", M["leather"], 3.72, 4.26, 0.32, 0.60, 0.88, 0.98)
    box("Arm_RestS", M["leather"], 3.72, 4.26, 0.32, 0.60, 1.48, 1.58)
    box("Arm_Seat", M["leather"], 3.72, 4.26, 0.32, 0.46, 0.98, 1.48)
    box("Arm_BackCush", M["leather"], 4.20, 4.26, 0.46, 0.80, 1.02, 1.44)

    # side table + pouf
    cyl("Side_Top", M["marble"], 3.55, 0.49, 0.38, 0.20, 0.03)
    cyl("Side_Stem", M["black"], 3.55, 0.235, 0.38, 0.02, 0.47)
    cyl("Side_Base", M["black"], 3.55, 0.01, 0.38, 0.12, 0.02)
    cyl("Pouf", M["sage"], 4.05, 0.20, 0.48, 0.22, 0.40)

    # divider storage unit by the dining (plan: 0.43 x 1.43 at X 4.77-5.20)
    box("Divider_Plinth", M["black"], 4.80, 5.17, 0, 0.10, 0.03, 1.40)
    box("Divider_Body", M["walnut"], 4.77, 5.20, 0.10, 1.00, 0.0, 1.43)
    box("Divider_Top", M["slat"], 4.77, 5.20, 1.00, 1.04, 0.0, 1.43)

    # TV wall (partition living face Z=2.34)
    box("TV_Panel_Sage", M["accent"], 1.40, 3.00, 0.09, 2.60, 2.32, ZP0)
    box("TV_Panel_Oak", M["slat"], 1.05, 1.40, 0.09, 2.60, 2.32, ZP0)
    for i, x in enumerate((1.41, 2.61)):
        pass
    for i, (x, z) in enumerate([(1.42, 2.04), (2.84, 2.04), (1.42, 2.28), (2.84, 2.28)]):
        box(f"TV_Leg{i}", M["black"], x - 0.02, x + 0.02, 0, 0.15, z - 0.02, z + 0.02)
    box("TV_Console", M["walnut"], 1.38, 2.88, 0.15, 0.55, 2.00, 2.32)
    for i in range(4):
        a = 1.38 + i * 0.375
        box(f"TV_ConsoleDoor{i}", M["slat"], a + 0.003, a + 0.372, 0.17, 0.53, 1.98, 2.00)
    box("TV_Body", M["black"], 1.515, 2.745, 0.95, 1.66, 2.29, 2.32)
    box("TV_Screen", M["screen"], 1.525, 2.735, 0.96, 1.65, 2.285, 2.29)

    # dining table (X 6.24-7.13, Z 0.04-1.24) + 4 chairs
    box("Dining_Top", M["walnut"], 6.24, 7.13, 0.71, 0.75, 0.04, 1.24)
    for i, (x, z) in enumerate([(6.30, 0.10), (7.07, 0.10), (6.30, 1.18), (7.07, 1.18)]):
        box(f"Dining_Leg{i}", M["black"], x - 0.025, x + 0.025, 0, 0.71, z - 0.025, z + 0.025)
    for i, (cx, cz, f) in enumerate([(5.98, 0.32, 1), (5.98, 0.83, 1), (7.36, 0.32, -1), (7.36, 0.83, -1)]):
        chair(f"Chair{i}", cx, cz, f)
    # pendant
    cyl("Pend_Cord", M["black"], 6.685, 2.35, 0.64, 0.004, 1.00)
    cyl("Pend_Shade", M["brass"], 6.685, 1.78, 0.64, 0.20, 0.14)
    cyl("Pend_Bulb", M["light"], 6.685, 1.70, 0.64, 0.06, 0.04)


def chair(name, cx, cz, f):
    """dining chair 0.44 x 0.44; f=+1 faces +X (back at west), f=-1 faces -X."""
    s = 0.44
    x0, x1, z0, z1 = cx - s / 2, cx + s / 2, cz - s / 2, cz + s / 2
    box(name + "_Seat", M["leather"], x0, x1, 0.43, 0.47, z0, z1)
    bx0, bx1 = (x0, x0 + 0.03) if f > 0 else (x1 - 0.03, x1)
    fx0, fx1 = (x1 - 0.03, x1) if f > 0 else (x0, x0 + 0.03)
    for k, z in enumerate((z0, z1 - 0.03)):
        box(f"{name}_LegF{k}", M["black"], fx0, fx1, 0, 0.43, z, z + 0.03)
        box(f"{name}_PostB{k}", M["black"], bx0, bx1, 0, 0.88, z, z + 0.03)
    box(name + "_BackPad", M["leather"], bx0, bx1, 0.56, 0.86, z0 + 0.03, z1 - 0.03)


# ----------------------------------------------------------------- bedroom
def build_bedroom():
    box("Rug_Bed", M["rug_b"], 0.40, 3.00, 0.0, 0.012, 3.50, 4.80)
    # accent wall + headboard (head on south wall)
    box("Bed_AccentPanel", M["accent"], 0.55, 2.91, 0.09, 2.60, 5.08, D_IN)
    box("Bed_Headboard", M["headboard"], 0.75, 2.71, 0.30, 1.20, 4.98, 5.08)
    for i, (x, z) in enumerate([(0.86, 3.15), (2.60, 3.15), (0.86, 4.95), (2.60, 4.95)]):
        box(f"Bed_Foot{i}", M["black"], x - 0.03, x + 0.03, 0, 0.10, z - 0.03, z + 0.03)
    box("Bed_Base", M["walnut"], 0.83, 2.63, 0.10, 0.30, 3.12, 4.98)
    box("Bed_Mattress", M["linen"], 0.88, 2.58, 0.30, 0.56, 3.16, 4.96)
    box("Bed_Duvet", M["linen"], 0.86, 2.60, 0.50, 0.60, 3.14, 4.20)
    box("Bed_Throw", M["throw"], 0.855, 2.605, 0.50, 0.61, 3.50, 3.95)
    for i, x in enumerate((1.30, 2.16)):
        box(f"Bed_Pillow{i}", M["linen"], x - 0.32, x + 0.32, 0.56, 0.70, 4.55, 4.93)
        box(f"Bed_Cushion{i}", M["ochre"], x - 0.21, x + 0.21, 0.56, 0.84, 4.40, 4.52)
    # nightstands + lamps
    for tag, x0 in (("L", 0.30), ("R", 2.71)):
        box(f"Night_{tag}", M["walnut"], x0, x0 + 0.45, 0.15, 0.50, 4.66, 5.08)
        for i, (x, z) in enumerate([(x0 + 0.04, 4.70), (x0 + 0.41, 4.70), (x0 + 0.04, 5.04), (x0 + 0.41, 5.04)]):
            box(f"Night_{tag}_Leg{i}", M["black"], x - 0.015, x + 0.015, 0, 0.15, z - 0.015, z + 0.015)
        cyl(f"Lamp_{tag}_Base", M["brass"], x0 + 0.225, 0.61, 4.87, 0.05, 0.22)
        cyl(f"Lamp_{tag}_Shade", M["lamp_shade"], x0 + 0.225, 0.82, 4.87, 0.11, 0.20)
    # wardrobe (X 3.58-4.16, Z 3.30-5.10), doors face west
    box("Wardrobe_Body", M["walnut"], 3.58, XB0, 0.0, 2.80, 3.30, D_IN)
    fronts("Wardrobe", M["door"], 3.55, 3.58, -1, 3.30, D_IN, 0.02, 2.78, 3, "doors", hy=(1.00, 1.35))


# ----------------------------------------------------------------- kitchen
def build_kitchen():
    # --- WM nook (X 6.02-6.84, Z 2.46-3.15)
    box("WM_Body", M["white_app"], 6.06, 6.66, 0, 0.85, 2.52, 3.10)
    cyl("WM_Ring", M["steel"], 6.6675, 0.42, 2.81, 0.23, 0.015, axis="x")
    cyl("WM_Glass", M["screen"], 6.6825, 0.42, 2.81, 0.17, 0.015, axis="x")
    # --- fridge (Z 3.38-4.08) + loft
    box("Fridge_Body", M["steel"], 6.06, 6.76, 0, 1.82, 3.38, 4.08)
    box("Fridge_Seam", M["black"], 6.76, 6.765, 1.19, 1.21, 3.38, 4.08)
    box("Fridge_HandleUp", M["black"], 6.765, 6.795, 1.28, 1.72, 3.40, 3.42)
    box("Fridge_HandleLow", M["black"], 6.765, 6.795, 0.60, 1.05, 3.40, 3.42)
    box("Fridge_Loft", M["upper"], 6.02, 6.62, 1.92, 2.80, 3.30, 4.12)
    fronts("Fridge_LoftF", M["upper"], 6.62, 6.65, +1, 3.30, 4.12, 1.93, 2.79, 2, "doors", hy=(1.95, 2.15))
    # --- pantry (Z 4.18-5.10)
    box("Pantry_Body", M["upper"], 6.02, 6.62, 0, 2.80, 4.18, D_IN)
    fronts("Pantry", M["upper"], 6.62, 6.65, +1, 4.18, D_IN, 0.02, 2.78, 2, "doors", hy=(1.00, 1.35))

    # --- east run: modules along Z (X 7.78-8.35 carcass, fronts at 7.74-7.78, worktop to 7.73)
    X0, X1 = 7.78, W_IN
    mods = [(2.46, 3.06, "drawers", 3), (3.06, 3.86, "doors", 2), (3.86, 4.46, "drawers", 3), (4.46, D_IN, "doors", 2)]
    box("Kitchen_Plinth", M["skirt"], 7.80, X1, 0, 0.10, 2.46, D_IN)
    for i, (za, zb, mode, n) in enumerate(mods):
        top = 0.70 if i == 1 else 0.86                           # sink module is lower: basin sits in it
        box(f"Kit_Carcass{i}", M["walnut"], X0, X1, 0.10, top, za, zb)
        fronts(f"Kit_Front{i}", M["walnut"], 7.74, 7.78, -1, za, zb, 0.12, 0.85, n, mode)
    # worktop (marble) with real sink cut-out X 7.86-8.24, Z 3.17-3.75
    box("Top_A", M["marble"], 7.73, X1, 0.86, 0.90, 2.46, 3.17)
    box("Top_B", M["marble"], 7.73, X1, 0.86, 0.90, 3.75, D_IN)
    box("Top_Front", M["marble"], 7.73, 7.86, 0.86, 0.90, 3.17, 3.75)
    box("Top_Back", M["marble"], 8.24, X1, 0.86, 0.90, 3.17, 3.75)
    # basin (stainless): floor + 4 walls
    box("Sink_Floor", M["steel"], 7.86, 8.24, 0.70, 0.72, 3.17, 3.75)
    box("Sink_WallF", M["steel"], 7.86, 7.872, 0.72, 0.90, 3.17, 3.75)
    box("Sink_WallB", M["steel"], 8.228, 8.24, 0.72, 0.90, 3.17, 3.75)
    box("Sink_WallN", M["steel"], 7.872, 8.228, 0.72, 0.90, 3.17, 3.182)
    box("Sink_WallS", M["steel"], 7.872, 8.228, 0.72, 0.90, 3.738, 3.75)
    cyl("Sink_Drain", M["black"], 8.05, 0.722, 3.46, 0.03, 0.004)
    # tap
    cyl("Tap_Stem", M["brass"], 8.30, 1.05, 3.46, 0.013, 0.30)
    box("Tap_Spout", M["brass"], 8.10, 8.313, 1.18, 1.21, 3.45, 3.47)
    # splash-backs (flush to east wall)
    box("Splash_Low", M["marble"], 8.33, X1, 0.90, 1.10, 2.46, D_IN)
    box("Splash_Hob", M["marble"], 8.33, X1, 1.10, 1.40, 3.86, 4.46)
    # hob
    box("Hob_Glass", M["hob"], 7.80, 8.30, 0.90, 0.905, 3.90, 4.42)
    for i, (x, z) in enumerate([(7.95, 4.03), (7.95, 4.29), (8.17, 4.03), (8.17, 4.29)]):
        cyl(f"Hob_Ring{i}", M["brass"], x, 0.908, z, 0.055, 0.006)
        cyl(f"Hob_Cap{i}", M["black"], x, 0.9115, z, 0.040, 0.007)
    # hood + chimney, upper cabinets (only on the solid wall segment)
    box("Hood_Body", M["black"], 7.95, X1, 1.40, 1.52, 3.86, 4.46)
    box("Hood_Chimney", M["black"], 8.20, X1, 1.52, H_WALL, 3.96, 4.36)
    box("Upper_Carcass", M["upper"], 8.05, X1, 1.45, 2.25, 4.46, D_IN)
    fronts("Upper_Front", M["upper"], 8.02, 8.05, -1, 4.46, D_IN, 1.46, 2.24, 2, "doors", hy=(1.50, 1.75))


# ----------------------------------------------------------------- toilet (X 4.28-5.90, Z 2.46-4.30)
def build_toilet():
    # walk-in shower (X 4.28-5.00, Z 2.46-3.20), open on the east side
    box("Shower_Tray", M["ceramic"], XB1, 5.00, 0, 0.03, ZP1, 3.20)
    cyl("Shower_Drain", M["brass"], 4.64, 0.032, 2.83, 0.04, 0.004)
    box("Shower_Glass", M["glass"], XB1, 5.00, 0.03, 2.00, 3.19, 3.21)
    box("Shower_GlassTop", M["black"], XB1, 5.00, 2.00, 2.03, 3.185, 3.215)
    box("Shower_Arm", M["brass"], XB1, 4.58, 2.04, 2.06, 2.82, 2.84)
    cyl("Shower_Head", M["brass"], 4.62, 2.035, 2.83, 0.12, 0.015)
    # vanity against shaft wall (south): wall-hung unit + vessel basin + mirror
    box("Vanity_Body", M["walnut"], XB1, 5.05, 0.35, 0.78, 3.75, ZS0)
    box("Vanity_Top", M["marble"], XB1, 5.05, 0.78, 0.82, 3.75, ZS0)
    cyl("Vanity_Basin", M["ceramic"], 4.665, 0.88, 4.02, 0.17, 0.12)
    cyl("Vanity_Tap", M["brass"], 4.665, 0.93, 4.22, 0.012, 0.22)
    box("Vanity_Spout", M["brass"], 4.655, 4.675, 1.03, 1.05, 4.10, 4.22)
    box("Vanity_Mirror", M["mirror"], 4.38, 4.95, 1.10, 1.95, 4.27, ZS0)
    # WC against east wall, facing west
    cyl("WC_Pan", M["ceramic"], 5.42, 0.21, 3.92, 0.19, 0.42, scale=(1.26, 1, 1))
    cyl("WC_Seat", M["ceramic"], 5.42, 0.44, 3.92, 0.19, 0.04, scale=(1.26, 1, 1))
    box("WC_Tank", M["ceramic"], 5.66, XK0, 0.0, 0.80, 3.74, 4.10)
    cyl("WC_Button", M["brass"], 5.78, 0.815, 3.92, 0.025, 0.03)


# ----------------------------------------------------------------- balcony
def build_balcony():
    xe = 9.92
    # glass balustrade (east + south), corner posts, base channel, handrail
    for i, (px, pz) in enumerate([(xe - 0.06, 0.0), (xe - 0.06, D_IN - 0.06), (BAL_X0, D_IN - 0.06)]):
        box(f"Bal_Post{i}", M["black"], px, px + 0.06, 0, 1.04, pz, pz + 0.06)
    box("Bal_E_Channel", M["black"], xe - 0.055, xe - 0.005, 0, 0.06, 0.06, D_IN - 0.06)
    box("Bal_E_Glass", M["glass"], xe - 0.04, xe - 0.02, 0.06, 1.04, 0.06, D_IN - 0.06)
    box("Bal_E_Rail", M["black"], xe - 0.06, xe, 1.04, 1.09, 0.0, D_IN)
    box("Bal_S_Channel", M["black"], BAL_X0 + 0.06, xe - 0.06, 0, 0.06, D_IN - 0.055, D_IN - 0.005)
    box("Bal_S_Glass", M["glass"], BAL_X0 + 0.06, xe - 0.06, 0.06, 1.04, D_IN - 0.04, D_IN - 0.02)
    box("Bal_S_Rail", M["black"], BAL_X0, xe - 0.06, 1.04, 1.09, D_IN - 0.06, D_IN)
    # planters
    for tag, z0 in (("N", 0.30), ("S", 3.60)):
        box(f"Planter_{tag}", M["pot"], 9.48, 9.84, 0, 0.42, z0, z0 + 1.20)
        for k, (dx, dz, r, hh, m_) in enumerate([(0.0, 0.2, 0.20, 0.60, "leaf"), (0.0, 0.55, 0.26, 0.78, "leaf2"),
                                                 (0.0, 0.90, 0.20, 0.62, "leaf"), (0.05, 0.38, 0.17, 0.95, "leaf2"),
                                                 (-0.02, 0.75, 0.16, 0.98, "leaf")]):
            ball(f"Plant_{tag}{k}", M[m_], 9.66 + dx, 0.42 + hh * 0.55, z0 + dz, r, sy=1.2)
    # bistro set
    cyl("Bistro_Top", M["black"], 9.05, 0.55, 2.55, 0.30, 0.03)
    cyl("Bistro_Stem", M["black"], 9.05, 0.275, 2.55, 0.02, 0.55)
    cyl("Bistro_Base", M["black"], 9.05, 0.01, 2.55, 0.18, 0.02)
    for i, z in enumerate((1.95, 3.15)):
        cyl(f"Stool_Seat{i}", M["leather"], 9.10, 0.44, z, 0.16, 0.04)
        cyl(f"Stool_Leg{i}", M["black"], 9.10, 0.21, z, 0.02, 0.42)


# ----------------------------------------------------------------- main
def run(out_path, ground=False, ceiling=True):
    build_shell(ceiling)
    build_living()
    build_bedroom()
    build_kitchen()
    build_toilet()
    build_balcony()
    if ground:
        box("Ground", M["ground"], -12, 25, -3.35, -3.15, -12, 18)

    scene = trimesh.Scene()
    for mesh, name in PARTS:
        scene.add_geometry(mesh, node_name=name, geom_name=name)
    glb = trimesh.exchange.gltf.export_glb(scene)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "wb") as f:
        f.write(glb)
    b = scene.bounds
    print(f"Wrote {out_path}")
    print(f"  nodes: {len(PARTS)}   size: {len(glb)/1024:.1f} KB")
    print(f"  bounds X {b[0][0]:.2f}..{b[1][0]:.2f}  Y {b[0][1]:.2f}..{b[1][1]:.2f}  Z {b[0][2]:.2f}..{b[1][2]:.2f}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "models", "unit_3.glb"))
    ap.add_argument("--ground", action="store_true", help="add a lawn plane 3.2 m below")
    ap.add_argument("--no-ceiling", action="store_true")
    a = ap.parse_args()
    run(a.out, a.ground, not a.no_ceiling)
